# Generated by Django 4.2.16 on 2026-07-22 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_visible', models.BooleanField(default=True)),
                ('penalty_minutes', models.PositiveIntegerField(default=20, help_text='Penalty minutes added per wrong try before the AC.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Short unique code shown in URLs, e.g. SUM01', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('statement', models.TextField(help_text='Problem statement. Plain text — a blank line starts a new paragraph.')),
                ('input_format', models.TextField(blank=True, verbose_name='Input')),
                ('output_format', models.TextField(blank=True, verbose_name='Output')),
                ('constraints', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True, help_text='Optional hint shown behind a spoiler on the problem page.')),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1)),
                ('tags', models.CharField(blank=True, help_text='Comma separated, e.g. math, greedy', max_length=200)),
                ('time_limit', models.FloatField(default=1.0, help_text='Seconds per test case')),
                ('memory_limit', models.PositiveIntegerField(default=256, help_text='Megabytes')),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to hide from the public list (e.g. for upcoming contests).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, verbose_name='Input')),
                ('expected_output', models.TextField(verbose_name='Expected output')),
                ('is_sample', models.BooleanField(default=False, help_text='Sample tests are shown on the problem page.')),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation shown with sample tests.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='judge.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('py', 'Python 3')], max_length=4)),
                ('source_code', models.TextField()),
                ('verdict', models.CharField(choices=[('PD', 'Pending'), ('JG', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('IE', 'Internal Error')], default='PD', max_length=4)),
                ('exec_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('first_fail_test', models.PositiveIntegerField(blank=True, null=True)),
                ('compile_message', models.TextField(blank=True)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('suggestion', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='judge.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='judge.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A, B, C …', max_length=4)),
                ('points', models.PositiveIntegerField(default=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='judge.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('contest', 'label'), ('contest', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests', through='judge.ContestProblem', to='judge.problem'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='judge.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
