# Generated by Django 4.2.16 on 2026-07-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='editorial',
            field=models.TextField(blank=True, help_text='Solution explanation. Unlocks for users who solved the problem (hidden for everyone while a contest containing it is running).'),
        ),
        migrations.AddField(
            model_name='problem',
            name='editorial_code',
            field=models.TextField(blank=True, help_text='Optional reference implementation shown with the editorial.', verbose_name='Reference solution'),
        ),
        migrations.AddField(
            model_name='problem',
            name='editorial_language',
            field=models.CharField(blank=True, choices=[('c', 'C'), ('cpp', 'C++'), ('py', 'Python 3')], help_text='Language of the reference solution.', max_length=4),
        ),
    ]
