# Generated by Django
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_update_models'), # Thay tên file migration trước đó của bạn vào đây
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='group_id',
            field=models.IntegerField(blank=True, null=True), # Hoặc kiểu dữ liệu tương ứng với code models.py của bạn
        ),
    ]
